// FluidSimulation.compute

#pragma kernel DiffusionDensity
#pragma kernel DiffusionVelocity
#pragma kernel AdvectionDensity
#pragma kernel AdvectionVelocity
#pragma kernel Projection1
#pragma kernel Projection2
#pragma kernel Projection3
#pragma kernel SetBounds
#pragma kernel TextureSet
#pragma kernel AddValue
#pragma kernel AddVelocity

uint Width;
uint Height;

int indicator;
float value;
float velocity;

float dt;
float spread;
float hitPosX;
float hitPosY;
float xAmount;
float yAmount;

RWTexture2D<float4> _In;  // Input Texture
RWTexture2D<float4> _Out;  // Output Texture
RWTexture2D<float4> _OutTemp;  // Velocity Texture


[numthreads(8, 8, 1)]
void DiffusionDensity(int2 id : SV_DispatchThreadID)
{
	int Width, Height;
	_Out.GetDimensions(Width, Height);
	int2 dim = int2(Width, Height);
	if (any(id >= dim))
	{
		return;
	}

    float4 Result = _OutTemp[id];
    float a = dt * spread * (Width - 2) * (Height - 2);
    Result.r =
		(_In[id].r + 
			a * (_OutTemp[id + uint2(1, 0)].r + 
            _OutTemp[id - uint2(1, 0)].r + 
            _OutTemp[id + uint2(0, 1)].r + 
            _OutTemp[id - uint2(0, 1)].r
		))  / (1 + 4 * a);
    _Out[id] = Result;
}

[numthreads(8, 8, 1)]
void DiffusionVelocity(int2 id : SV_DispatchThreadID)
{
	int Width, Height;
	_Out.GetDimensions(Width, Height);
	int2 dim = int2(Width, Height);
	if (any(id >= dim))
	{
		return;
	}
    
     float4 Result = _OutTemp[id];
     float a = dt * spread * (Width - 2) * (Height - 2);
     Result.gb =
		(_In[id].gb + 
			a * (_OutTemp[id + uint2(1, 0)].gb + 
            _OutTemp[id - uint2(1, 0)].gb + 
            _OutTemp[id + uint2(0, 1)].gb + 
            _OutTemp[id - uint2(0, 1)].gb
		))  / (1 + 4 * a);

        _Out[id] = Result;
}

[numthreads(8, 8, 1)]
void AdvectionDensity(int2 id : SV_DispatchThreadID)
{
	int Width, Height;
	_Out.GetDimensions(Width, Height);
	int2 dim = int2(Width, Height);
	if (any(id >= dim))
	{
		return;
	}

    float2 deltaTimeScaled = dt * int2(Width - 2, Height - 2); // Scale the time step by the grid dimensions
    float2 newPosition = float2(id) - deltaTimeScaled * float2(_OutTemp[id].g, _OutTemp[id].b); // Calculate new position based on velocity
    newPosition.x = clamp(newPosition.x, 0.5, (Width - 2) + 0.5); // Clamp x position to stay within grid bounds
    newPosition.y = clamp(newPosition.y, 0.5, (Height - 2) + 0.5); // Clamp y position to stay within grid bounds

    uint2 lowerBound = (uint2)newPosition; // Lower bound of the grid cell
    uint2 upperBound = lowerBound + 1; // Upper bound of the grid cell

    float2 fractionalPart = newPosition - lowerBound; // Fractional part for interpolation  |-o  |
    float2 oneMinusFractional = 1.0 - fractionalPart; // One minus the fractional part      | o--|

    float4 interpolatedResult = _OutTemp[id]; // Initialize result with the current value
    interpolatedResult.r = 
        oneMinusFractional.x * (oneMinusFractional.y * _In[lowerBound].r +
                                fractionalPart.y * _In[uint2(lowerBound.x, upperBound.y)].r) +
        fractionalPart.x * (oneMinusFractional.y * _In[uint2(upperBound.x, lowerBound.y)].r +
                            fractionalPart.y * _In[upperBound].r);

    _Out[id] = interpolatedResult; // Write the interpolated result back to the output texture
}

[numthreads(8, 8, 1)]
void AdvectionVelocity(int2 id : SV_DispatchThreadID)
{
	int Width, Height;
	_Out.GetDimensions(Width, Height);
	int2 dim = int2(Width, Height);
	if (any(id >= dim))
	{
		return;
	}

    float2 deltaTimeScaled = dt * int2(Width - 2, Height - 2); // Scale the time step by the grid dimensions
    float2 newPosition = float2(id) - deltaTimeScaled * float2(_In[id].g, _In[id].b); // Calculate new position based on velocity
    newPosition.x = clamp(newPosition.x, 0.5, (Width - 2) + 0.5); // Clamp x position to stay within grid bounds
    newPosition.y = clamp(newPosition.y, 0.5, (Height - 2) + 0.5); // Clamp y position to stay within grid bounds

    uint2 lowerBound = (uint2)newPosition; // Lower bound of the grid cell
    uint2 upperBound = lowerBound + 1; // Upper bound of the grid cell

    float2 fractionalPart = newPosition - lowerBound; // Fractional part for interpolation  |-o  |
    float2 oneMinusFractional = 1.0 - fractionalPart; // One minus the fractional part      | o--|

    float4 interpolatedResult = _OutTemp[id]; // Initialize result with the current value
    interpolatedResult.gb = 
        oneMinusFractional.x * (oneMinusFractional.y * _In[lowerBound].gb +
                                fractionalPart.y * _In[uint2(lowerBound.x, upperBound.y)].gb) +
        fractionalPart.x * (oneMinusFractional.y * _In[uint2(upperBound.x, lowerBound.y)].gb +
                            fractionalPart.y * _In[upperBound].gb);
    _Out[id] = interpolatedResult; // Write the interpolated result back to the output texture

    
}

[numthreads(8, 8, 1)]
void Projection1(int2 id : SV_DispatchThreadID) 
{
	int Width, Height;
	_In.GetDimensions(Width, Height);
	int2 dim = int2(Width, Height);
	if (any(id >= dim))
	{
		return;
	}
	
	//In.g = pressure = 0
    //In.b = divergence =>
    /*_Temp[id] = float4(GetPrevState(id, dim).r, 0, -0.5f *
                ((_Out[int2(id.x+1, id.y)].g -
                _Out[int2(id.x-1, id.y)].g)/Scale +
                (_Out[int2(id.x, id.y+1)].b -
                _Out[int2(id.x, id.y-1)].b)/Scale),
                GetPrevState(id, dim).a);
*/
				
        
    float4 Result = _In[id];
	Result.g = 0; //pressure = 0

	Result.b = -0.5f * ( //divergence
        (_OutTemp[int2(id.x+1, id.y)].g - _OutTemp[int2(id.x-1, id.y)].g)/Width +
        (_OutTemp[int2(id.x, id.y+1)].b - _OutTemp[int2(id.x, id.y-1)].b)/Height
    );

    _In[id] = Result;
}

[numthreads(8, 8, 1)]
void Projection2(int2 id : SV_DispatchThreadID) 
{int Width, Height;
	_In.GetDimensions(Width, Height);
	int2 dim = int2(Width, Height);
	if (any(id >= dim))
	{
		return;
	}

	float4 Result = _OutTemp[id];
	Result.g = (_In[id].b +
		(_In[int2(id.x+1, id.y)].g + _In[int2(id.x-1, id.y)].g + 
			_In[int2(id.x, id.y+1)].g + _In[int2(id.x, id.y-1)].g)
		) * 0.25f;
	
	_OutTemp[id] = Result;
}

[numthreads(8, 8, 1)]
void Projection3(int2 id : SV_DispatchThreadID) 
{
	int Width, Height;
	_Out.GetDimensions(Width, Height);
	int2 dim = int2(Width, Height);
	if (any(id >= dim))
	{
		return;
	}

	float2 gradient = float2(
        0.5f * (_In[int2(id.x+1, id.y)].g - _In[int2(id.x-1, id.y)].g) * (Width),
        0.5f * (_In[int2(id.x, id.y+1)].g - _In[int2(id.x, id.y-1)].g) * (Height));

    float4 Result = _Out[id];
	Result.g = _OutTemp[id].g - gradient.x;
	Result.b = _OutTemp[id].b - gradient.y;

    _Out[id] = Result;
}

[numthreads(8, 8, 1)]
void SetBounds(int2 id : SV_DispatchThreadID)
{
    if (id.x < Width && id.y == 0) // bottom boundary
    {
        if (_Out[int2(id.x, 0)].b < 0) // if velocity is downwards
        {
            _Out[int2(id.x, 0)] = float4(_Out[int2(id.x, 0)].rg, -_Out[int2(id.x, 0)].b, _Out[int2(id.x, 0)].a);
        }
    }
    else if (id.x < Width && id.y == Height - 1) // top boundary
    {
        if (_Out[int2(id.x, Height - 1)].b > 0) // if velocity is upwards
        {
            _Out[int2(id.x, Height - 1)] = float4(_Out[int2(id.x, Height - 1)].rg, -_Out[int2(id.x, Height - 1)].b, _Out[int2(id.x, Height - 1)].a);
        }
    }

    if (id.x == 0 && id.y < Height) // left boundary
    {
        if (_Out[int2(0, id.y)].g < 0) // if velocity is leftwards
        {
            _Out[int2(0, id.y)] = float4(_Out[int2(0, id.y)].r, -_Out[int2(0, id.y)].g, _Out[int2(0, id.y)].ba);
        }
    }
    else if (id.x == Width - 1 && id.y < Height) // right boundary
    {
        if (_Out[int2(Width - 1, id.y)].g > 0) // if velocity is rightwards
        {
            _Out[int2(Width - 1, id.y)] = float4(_Out[int2(Width - 1, id.y)].r, -_Out[int2(Width - 1, id.y)].g, _Out[int2(Width - 1, id.y)].ba);
        }
    }
}

[numthreads(8, 8, 1)]
void TextureSet(int2 id : SV_DispatchThreadID)
{
    /*
    if (id.x == 50 && id.y == 50){
        _Out[id] = float4(1000, 100, 0, _Out[id].a);
    }*/
}

[numthreads(1, 1, 1)]
void AddValue(int2 id : SV_DispatchThreadID)
{
	_Out[int2(hitPosX, hitPosY)] = float4(
        _Out[int2(hitPosX, hitPosY)].r + value, 
        _Out[int2(hitPosX, hitPosY)].gba);

    _Out[int2(hitPosX+1, hitPosY)] = float4(
        _Out[int2(hitPosX+1, hitPosY)].r + value, 
        _Out[int2(hitPosX+1, hitPosY)].gba);
            
    _Out[int2(hitPosX-1, hitPosY)] = float4(
        _Out[int2(hitPosX-1, hitPosY)].r + value, 
        _Out[int2(hitPosX-1, hitPosY)].gba);
        
    _Out[int2(hitPosX, hitPosY+1)] = float4(
        _Out[int2(hitPosX, hitPosY+1)].r + value, 
        _Out[int2(hitPosX, hitPosY+1)].gba);
        
    _Out[int2(hitPosX, hitPosY-1)] = float4(
        _Out[int2(hitPosX, hitPosY-1)].r + value, 
        _Out[int2(hitPosX, hitPosY-1)].gba);
}

[numthreads(1, 1, 1)]
void AddVelocity(int2 id : SV_DispatchThreadID)
{
	float u = 0;//value + value * sqrt( xAmount*xAmount + yAmount*yAmount ); //density aka concentration
	float vx = xAmount * velocity;
	float vy = yAmount * velocity;

	//3x3 grid
	int2 p0 = int2(hitPosX, hitPosY);
	int2 p1 = int2(hitPosX+1, hitPosY);
	int2 p2 = int2(hitPosX-1, hitPosY);
	int2 p3 = int2(hitPosX, hitPosY+1);
	int2 p4 = int2(hitPosX, hitPosY-1);
	int2 p5 = int2(hitPosX+1, hitPosY+1);
	int2 p6 = int2(hitPosX-1, hitPosY+1);
	int2 p7 = int2(hitPosX+1, hitPosY-1);
	int2 p8 = int2(hitPosX-1, hitPosY-1);

	//circle outside 3x3 grid
	int2 q0 = int2(hitPosX+2, hitPosY+1);
	int2 q1 = int2(hitPosX+2, hitPosY);
	int2 q2 = int2(hitPosX+2, hitPosY-1);
	int2 q3 = int2(hitPosX-2, hitPosY+1);
	int2 q4 = int2(hitPosX-2, hitPosY);
	int2 q5 = int2(hitPosX-2, hitPosY-1);
	int2 q6 = int2(hitPosX+1, hitPosY+2);
	int2 q7 = int2(hitPosX, hitPosY+2);
	int2 q8 = int2(hitPosX-1, hitPosY+2);
	int2 q9 = int2(hitPosX+1, hitPosY-2);
	int2 qX = int2(hitPosX, hitPosY-2);
	int2 qE = int2(hitPosX-1, hitPosY-2);
	
	_Out[p0] = float4(_Out[p0].r+u, _Out[p0].g+vx, _Out[p0].b+vy, _Out[p0].a);
	_Out[p1] = float4(_Out[p1].r+u, _Out[p1].g+vx, _Out[p1].b+vy, _Out[p1].a);
	_Out[p2] = float4(_Out[p2].r+u, _Out[p2].g+vx, _Out[p2].b+vy, _Out[p2].a);
	_Out[p3] = float4(_Out[p3].r+u, _Out[p3].g+vx, _Out[p3].b+vy, _Out[p3].a);
	_Out[p4] = float4(_Out[p4].r+u, _Out[p4].g+vx, _Out[p4].b+vy, _Out[p4].a);
	_Out[p5] = float4(_Out[p5].r+u, _Out[p5].g+vx, _Out[p5].b+vy, _Out[p5].a);
	_Out[p6] = float4(_Out[p6].r+u, _Out[p6].g+vx, _Out[p6].b+vy, _Out[p6].a);
	_Out[p7] = float4(_Out[p7].r+u, _Out[p7].g+vx, _Out[p7].b+vy, _Out[p7].a);
	_Out[p8] = float4(_Out[p8].r+u, _Out[p8].g+vx, _Out[p8].b+vy, _Out[p8].a);

	_Out[q0] = float4(_Out[q0].r+u, _Out[q0].g+vx, _Out[q0].b+vy, _Out[q0].a);
	_Out[q1] = float4(_Out[q1].r+u, _Out[q1].g+vx, _Out[q1].b+vy, _Out[q1].a);
	_Out[q2] = float4(_Out[q2].r+u, _Out[q2].g+vx, _Out[q2].b+vy, _Out[q2].a);
	_Out[q3] = float4(_Out[q3].r+u, _Out[q3].g+vx, _Out[q3].b+vy, _Out[q3].a);
	_Out[q4] = float4(_Out[q4].r+u, _Out[q4].g+vx, _Out[q4].b+vy, _Out[q4].a);
	_Out[q5] = float4(_Out[q5].r+u, _Out[q5].g+vx, _Out[q5].b+vy, _Out[q5].a);
	_Out[q6] = float4(_Out[q6].r+u, _Out[q6].g+vx, _Out[q6].b+vy, _Out[q6].a);
	_Out[q7] = float4(_Out[q7].r+u, _Out[q7].g+vx, _Out[q7].b+vy, _Out[q7].a);
	_Out[q8] = float4(_Out[q8].r+u, _Out[q8].g+vx, _Out[q8].b+vy, _Out[q8].a);
	_Out[q9] = float4(_Out[q9].r+u, _Out[q9].g+vx, _Out[q9].b+vy, _Out[q9].a);
	_Out[qX] = float4(_Out[qX].r+u, _Out[qX].g+vx, _Out[qX].b+vy, _Out[qX].a);
	_Out[qE] = float4(_Out[qE].r+u, _Out[qE].g+vx, _Out[qE].b+vy, _Out[qE].a);
	
	
}